package exiflab.spike

import com.drew.imaging.ImageMetadataReader
import com.drew.metadata.xmp.XmpDirectory
import org.apache.commons.imaging.Imaging
import org.apache.commons.imaging.bytesource.ByteSource
import org.apache.commons.imaging.formats.jpeg.JpegImageMetadata
import org.apache.commons.imaging.formats.jpeg.exif.ExifRewriter
import org.apache.commons.imaging.formats.tiff.TiffImageMetadata
import org.apache.commons.imaging.formats.tiff.TiffImageParser
import org.apache.commons.imaging.formats.tiff.constants.ExifTagConstants
import org.apache.commons.imaging.formats.tiff.constants.TiffTagConstants
import org.apache.commons.imaging.formats.tiff.write.TiffImageWriterLossless
import org.apache.commons.imaging.formats.tiff.write.TiffOutputSet
import java.io.ByteArrayOutputStream
import java.io.File
import kotlin.math.abs

const val ARTIST = "Spike Artist"
const val DTO = "2001:02:03 04:05:06"
const val LAT = 57.70887 // Gothenburg
const val LON = 11.97456

fun main(args: Array<String>) {
    val samples = File(args.getOrElse(0) { "samples" })
    val outDir = File(args.getOrElse(1) { "build/spike-out" }).apply { mkdirs() }
    val resultsDir = File(args.getOrElse(2) { "results" }).apply { mkdirs() }
    val files = samples.listFiles { f -> f.isFile && !f.name.startsWith(".") && f.extension.lowercase() != "md" }!!
        .sortedBy { it.name }

    println("exiftool ${Exiftool.version}, ${files.size} sample files")
    val baseline = files.associateWith { Exiftool.tags(it) }

    File(resultsDir, "read-results.md").writeText(readReport(files, baseline))
    File(resultsDir, "write-results.md").writeText(writeReport(files, baseline, outDir))
    File(resultsDir, "scenario-results.md").writeText(
        "# Scenario results\n\n" + stripGpsReport(files, baseline, outDir) + "\n" +
            sidecarReport(files, baseline, outDir) + "\n" + xmpParseReport(files),
    )
    println("done -> ${resultsDir.absolutePath}")
}

// ---------------------------------------------------------------- read

private fun category(dirClass: String): String = when {
    dirClass.contains("Makernote") -> "MakerNotes"
    dirClass in setOf("ExifIFD0Directory", "ExifSubIFDDirectory", "ExifInteropDirectory", "ExifThumbnailDirectory", "GpsDirectory", "ExifImageDirectory") -> "EXIF"
    dirClass == "XmpDirectory" -> "XMP"
    dirClass == "IptcDirectory" -> "IPTC"
    dirClass == "IccDirectory" -> "ICC_Profile"
    else -> "Other"
}

private fun readReport(files: List<File>, baseline: Map<File, Map<String, String>>): String {
    val sb = StringBuilder()
    sb.appendLine("# Read results")
    sb.appendLine()
    sb.appendLine("Generated by `spike` (`gradle run`). exiftool ${Exiftool.version} is the reference. Counts are tags per family-0 group;")
    sb.appendLine("the libraries count differently (exiftool expands sub-structures), so the numbers show *coverage*, not equality.")
    sb.appendLine("`-` = group not present / not found.")
    sb.appendLine()
    sb.appendLine("| File | Type | EXIF et / me | MakerNotes et / me | XMP et / me | IPTC et / me | ICC et / me | metadata-extractor notes | Commons Imaging |")
    sb.appendLine("|---|---|---|---|---|---|---|---|---|")
    for (f in files) {
        val et = baseline.getValue(f).countByFamily0()
        val type = baseline.getValue(f)["File:System:FileType"] ?: baseline.getValue(f).entries.firstOrNull { it.key.endsWith(":FileType") }?.value ?: "?"
        val me = HashMap<String, Int>()
        val meNotes = StringBuilder()
        try {
            val md = ImageMetadataReader.readMetadata(f)
            for (d in md.directories) {
                val c = category(d.javaClass.simpleName)
                val n = if (d is XmpDirectory) d.xmpProperties.size else d.tagCount
                me.merge(c, n, Int::plus)
                if (c == "MakerNotes") meNotes.append(d.name.removeSuffix(" Makernote")).append(' ')
                if (d.hasErrors()) meNotes.append("err(${d.name}: ${d.errors.first().take(60)}) ")
            }
        } catch (t: Throwable) {
            meNotes.append("FAILED: ${t.javaClass.simpleName} ${t.message?.take(60)}")
        }
        val ci = try {
            when (val m = Imaging.getMetadata(f)) {
                null -> "no metadata"
                is JpegImageMetadata -> "ok, EXIF fields: ${m.exif?.allFields?.size ?: 0}"
                is TiffImageMetadata -> "ok, TIFF fields: ${m.allFields.size}"
                else -> "ok (${m.javaClass.simpleName}, ${m.items.size} items)"
            }
        } catch (t: Throwable) {
            "FAILED: ${t.javaClass.simpleName}"
        }
        fun cell(g: String) = "${et[g] ?: "-"} / ${me[g] ?: "-"}"
        sb.appendLine("| ${f.name} | $type | ${cell("EXIF")} | ${cell("MakerNotes")} | ${cell("XMP")} | ${cell("IPTC")} | ${cell("ICC_Profile")} | ${meNotes.toString().trim()} | $ci |")
    }
    return sb.toString()
}

// ---------------------------------------------------------------- write

internal enum class Kind { JPEG, PNG, WEBP, HEIF, TIFF_RAW, OTHER }

internal fun kindOf(tags: Map<String, String>): Kind {
    val t = tags["File:System:FileType"] ?: tags.entries.firstOrNull { it.key.endsWith(":FileType") }?.value ?: ""
    return when {
        t == "JPEG" -> Kind.JPEG
        t == "PNG" -> Kind.PNG
        t.contains("WEBP") -> Kind.WEBP
        t == "HEIC" || t == "HEIF" -> Kind.HEIF
        t in setOf("DNG", "CR2", "NEF", "RW2", "ARW", "ORF", "PEF", "SRW", "TIFF") -> Kind.TIFF_RAW
        else -> Kind.OTHER
    }
}

internal fun container(kind: Kind): ExifContainer? = when (kind) {
    Kind.JPEG -> JpegContainer
    Kind.PNG -> PngContainer
    Kind.WEBP -> WebpContainer
    Kind.HEIF -> HeifContainer
    Kind.TIFF_RAW -> TiffFileContainer
    Kind.OTHER -> null
}

private fun applyCommonsEdits(set: TiffOutputSet) {
    val root = set.orCreateRootDirectory
    root.removeField(TiffTagConstants.TIFF_TAG_ARTIST)
    root.add(TiffTagConstants.TIFF_TAG_ARTIST, ARTIST)
    val exif = set.orCreateExifDirectory
    exif.removeField(ExifTagConstants.EXIF_TAG_DATE_TIME_ORIGINAL)
    exif.add(ExifTagConstants.EXIF_TAG_DATE_TIME_ORIGINAL, DTO)
    set.setGpsInDegrees(LON, LAT)
}

private fun dms(v: Double): Array<Pair<Long, Long>> {
    val a = abs(v); val d = a.toLong(); val m = ((a - d) * 60).toLong(); val s = ((a - d) * 60 - m) * 60
    return arrayOf(d to 1L, m to 1L, Math.round(s * 1000) to 1000L)
}

private fun protoEdit(tiff: ByteArray?): ByteArray {
    val u = TiffAppendUpdater(tiff)
    return u.apply(
        TiffAppendUpdater.Edits(
            ifd0 = mapOf(0x013B to u.ascii(0x013B, ARTIST)),
            exif = mapOf(0x9003 to u.ascii(0x9003, DTO)),
            gps = listOf(
                u.bytes(0x0000, 2, 3, 0, 0),
                u.ascii(0x0001, "N"), u.rationals(0x0002, *dms(LAT)),
                u.ascii(0x0003, "E"), u.rationals(0x0004, *dms(LON)),
            ),
        ),
    )
}

private fun commonsTiffEdit(tiff: ByteArray?): ByteArray {
    val set = if (tiff == null) TiffOutputSet() else {
        val md = TiffImageParser().getMetadata(ByteSource.array(tiff), null) as TiffImageMetadata
        md.outputSet
    }
    applyCommonsEdits(set)
    val out = ByteArrayOutputStream()
    if (tiff == null) {
        org.apache.commons.imaging.formats.tiff.write.TiffImageWriterLossy(set.byteOrder).write(out, set)
    } else {
        TiffImageWriterLossless(set.byteOrder, tiff).write(out, set)
    }
    return out.toByteArray()
}

private class Writer(val name: String, val supports: (Kind) -> Boolean, val write: (File, Kind) -> ByteArray)

private val writers = listOf(
    Writer("commons-jpeg-lossless", { it == Kind.JPEG }) { f, _ ->
        val md = Imaging.getMetadata(f) as? JpegImageMetadata
        val set = md?.exif?.outputSet ?: TiffOutputSet()
        applyCommonsEdits(set)
        ByteArrayOutputStream().also { ExifRewriter().updateExifMetadataLossless(f, it, set) }.toByteArray()
    },
    Writer("commons-jpeg-lossy", { it == Kind.JPEG }) { f, _ ->
        val md = Imaging.getMetadata(f) as? JpegImageMetadata
        val set = md?.exif?.outputSet ?: TiffOutputSet()
        applyCommonsEdits(set)
        ByteArrayOutputStream().also { ExifRewriter().updateExifMetadataLossy(f, it, set) }.toByteArray()
    },
    Writer("commons-tiff + custom container", { it != Kind.OTHER }) { f, k ->
        val c = container(k)!!
        val bytes = f.readBytes()
        c.writeTiff(bytes, commonsTiffEdit(c.readTiff(bytes)))
    },
    Writer("append-only tiff + custom container", { it != Kind.OTHER }) { f, k ->
        val c = container(k)!!
        val bytes = f.readBytes()
        c.writeTiff(bytes, protoEdit(c.readTiff(bytes)))
    },
)

private fun writeReport(files: List<File>, baseline: Map<File, Map<String, String>>, outDir: File): String {
    val sb = StringBuilder()
    sb.appendLine("# Write results")
    sb.appendLine()
    sb.appendLine("Edit applied to every file: IFD0:Artist, ExifIFD:DateTimeOriginal, GPS lat/lon (+refs, version).")
    sb.appendLine("Each output is re-read with exiftool ${Exiftool.version} and compared to the original.")
    sb.appendLine()
    sb.appendLine("* **values** - the three edits read back correctly")
    sb.appendLine("* **pixels** - exiftool `ImageDataHash` (SHA-256 over the image data only) identical before/after")
    sb.appendLine("* **lost / changed** - non-edited tags that disappeared or changed value (offsets, file-system and composite tags excluded)")
    sb.appendLine("* **MakerNotes** - number of decoded MakerNote tags before -> after")
    sb.appendLine()
    sb.appendLine("| File | Writer | Result | values | pixels | lost | changed | MakerNotes | new warnings | size delta |")
    sb.appendLine("|---|---|---|---|---|---|---|---|---|---|")
    val details = StringBuilder()
    for (f in files) {
        val before = baseline.getValue(f)
        val kind = kindOf(before)
        for (w in writers.filter { it.supports(kind) }) {
            val outcome = try {
                val bytes = w.write(f, kind)
                val out = File(outDir, "${w.name.replace(Regex("[^a-z0-9]+"), "-")}__${f.name}")
                out.writeBytes(bytes)
                verify(before, out, f.length())
            } catch (t: Throwable) {
                WriteOutcome(ok = false, error = "${t.javaClass.simpleName}: ${t.message?.lineSequence()?.first()?.take(90)}")
            }
            if (!outcome.ok) {
                sb.appendLine("| ${f.name} | ${w.name} | refused/failed: ${outcome.error} | | | | | | | |")
                continue
            }
            val verdict = outcome.verdict()
            sb.appendLine(
                "| ${f.name} | ${w.name} | $verdict | ${yn(outcome.valuesOk)} | ${yn(outcome.pixelsOk)} | ${outcome.lost.size} | ${outcome.changed.size} | " +
                    "${outcome.makerBefore} -> ${outcome.makerAfter} | ${outcome.newWarnings.joinToString("; ").take(80)} | ${outcome.sizeDelta} |",
            )
            if (outcome.lost.isNotEmpty() || outcome.changed.isNotEmpty()) {
                details.appendLine("### ${f.name} / ${w.name}")
                if (outcome.lost.isNotEmpty()) details.appendLine("* lost (${outcome.lost.size}): " + outcome.lost.take(25).joinToString(", ") { "`$it`" } + if (outcome.lost.size > 25) " ..." else "")
                if (outcome.changed.isNotEmpty()) details.appendLine("* changed: " + outcome.changed.take(10).joinToString("; ") { "`$it`" } + if (outcome.changed.size > 10) " ..." else "")
                details.appendLine()
            }
        }
    }
    sb.appendLine()
    sb.appendLine("## Details of lost / changed tags")
    sb.appendLine()
    sb.append(details)
    return sb.toString()
}

